version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
       name: Chmod permissions
       command: sudo chmod +x ./gradlew
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Lint Tests
        command: ./gradlew lint test
    - store_artifacts:
        path: app/build/reports
        destination: reports
    - store_test_results:
        path: app/build/test-results
    - run:
        name: Build
        command: ./gradlew assembleRelease
    - store_artifacts:
        path: app/build/outputs/apk/release
        destination: release
    - deploy:
        name: Deploy APK.
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            bash ./scripts/deploy-fabric.sh
            bash ./scripts/deploy-appcenter.sh
          fi
